Controllers/AccessController.cs
using Microsoft.AspNetCore.Mvc;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using AuthProject.Models;
using AuthProject.Data;

namespace AuthProject.Controllers
{
    public class AccessController : Controller
    {
        private readonly AppDbContext _context;

        public AccessController(AppDbContext context)
        {
            _context = context;
        }


        public IActionResult Login()
        {
            ClaimsPrincipal claimUser = HttpContext.User;

            if (claimUser.Identity.IsAuthenticated)
                return RedirectToAction("Index", "Home");


            return View();
        }


        [HttpPost]


        public async Task<IActionResult> Login(Login modelLogin)
        {
            var role = _context.roles.Where(x => x.Email == modelLogin.Email && x.Password == modelLogin.PassWord).FirstOrDefault();
            if (role == null)
            {
                ViewData["ValidateMessage"] = "User not found";
                return View();
            }

            List<Claim> claims = new List<Claim>()
                {
                new Claim(ClaimTypes.NameIdentifier, modelLogin.Email),
          //    new Claim("OtherProperties", "Example Role"),
                new Claim(ClaimTypes.Role, role.RollName)
              };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            AuthenticationProperties properties = new AuthenticationProperties()
            {
                AllowRefresh = true,
                IsPersistent = modelLogin.KeepLoggedIn,
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity), properties);

            return RedirectToAction("Index" ,"Home");
        }


    }
}

Controllers/RoleController.cs
using AuthProject.Data;
using AuthProject.Interface;
using AuthProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging.Signing;
using System.Data;

namespace AuthProject.Controllers
{
    [Authorize(Roles = "Admin")]

    public class RoleController : Controller
    {
        private readonly IRole _role;
        //for testing 
        private readonly AppDbContext _context;

        public RoleController(IRole role, AppDbContext context)
        {
            _context = context;
            _role = role;
        }

        public async Task<IActionResult> Index()
        {
            List<Role> abc = new List<Role>();
            abc = await _role.GetAllRole();
            int count = _context.Database.ExecuteSqlRaw("EXEC CountRole");
            ViewBag.Count = count;
            return View(abc);

        }
        public IActionResult Create()
        {
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Create(Role role)
        {
            if (await _role.insertupdate(role))
            {
                return Json(new { success = true });
                // return RedirectToAction("Index");
            }
            return Json(new { success = false });
           // return View(role);
        }
        public async Task<IActionResult> Edit(int? id)
        {
            Role role = await _role.GetRoleById(id);
            return View(role);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Role role)
        {
            if (await _role.insertupdate(role))
            {

                return RedirectToAction("Index");
            }
            return View(role);
        }
        [HttpPost]
        public IActionResult Delete(int? id)
        {
            var abc= _context.roles.Where(x => x.Id == id).FirstOrDefault();
           
            if (abc != null)
            {
                return RedirectToAction("Index");

            }
            return View();
            
            
        }
        [HttpPost]
        public async Task<IActionResult> Index(string Email)
        {
            if (Email != null)
            {


                List<Role> roles = new List<Role>();

                SqlParameter emailParameter = new SqlParameter("@Email", SqlDbType.NVarChar, 50);
                emailParameter.Value = Email;



                roles = await _context.roles.FromSqlRaw("EXEC Sp_SearchRole @Email", emailParameter).ToListAsync();
                if (roles.Count != 0)
                {
                    return View(roles);
                }
            }
            TempData["User Not Found"] = "Not Found";
            return RedirectToAction("Index");
        }
    }
}

Controllers/StudentController.cs
using AuthProject.Data;
using AuthProject.Interface;
using AuthProject.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace AuthProject.Controllers
{
    

    public class StudentController : Controller
    {
        private readonly IStudent _student;
        
        public StudentController(IStudent student)
        {
            _student = student;
          
        }
       
        public async Task<IActionResult> Index()
        {
            List<Student> student = await _student.GetAllUser();
            return View(student);
       


            //var role = _context.roles("Exec [dbo].[Sp_SearchStudent]").ToList();


            //        SqlQuery<ObjectResult>("exec [dbo].[current_call] @call_id", new SqlParameter("call_id", c_id)).ToList();

            //


        }
        [Authorize(Roles = "Admin,User")]

        public async Task<IActionResult> Create(int id)
        {

           
            var student = await _student.GetStudentById(id);
            if (student == null)
            {
                if (id == 0)
                {
                    return View();
                }
                else
                {
                    TempData["NotExist"] = $"There is not student from the id={id}";
                    return RedirectToAction("Index");

                }

            }

            return View(student);
        }
        [Authorize(Roles = "Admin,User")]
        [HttpPost]
        public async Task<IActionResult> Create(Student student)
        {
            if (ModelState.IsValid)
            {


                if (await _student.InsertUpdate(student))
                {
                    return RedirectToAction("Index");
                }

            }

            TempData["NotExist"] = $"Already Existed or Invalid Input";
            return View(student);
        }
        //public async Task<IActionResult> Delete(int? id)
        //{

        //    Student student = await _student.ShowStudentById(id);

        //    return View(student);

        //}
        //[HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Admin,User")]
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {

            if (await _student.DeleteStudent(id))
            {
                return RedirectToAction("Index");
            }
            return View();

        }
        public async Task<IActionResult> Detail(int? id)
        {
            Student stu = await _student.Detail(id);
            return View(stu);
        }
        
       
    }

}

Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>

@{


}
<html lang="en" class="disable-scroll">
<head runat="server">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuthProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuthProject.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
   
    <link href="~/css/Images/tw.ico" rel="shortcut icon" type="image/x-icon" />
     
    
   
</head>
<body style="overflow: hidden;">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AuthProject</a>
                <a><i class="fa fa-calendar-o"></i>DATE TODAY: @DateTime.Now.ToString("yyyy/MM/dd")</a>
                <div class="col-md-2 col-sm-12">

                    <div class="logo">
                        <a href="@Url.Action("Index", "Home" )">
                            <img style="width: 55px; padding-right: 10px;" src="~/css/Images/mmm.gif" />
                        </a>
                    </div>
                   

                </div>
                <div class="col-md-2 col-sm-12">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">

                        <p> You Are @User.FindFirstValue(ClaimTypes.Role)</p>


                    </li>

                </ul>
                </div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="topnav-right" d-sm-inline-flex justify-content-between">

                    <ul class="navbar-nav flex-grow-1">


                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">

                                <p>HI @User.FindFirstValue(ClaimTypes.NameIdentifier)!</p>


                            </li>

                        }
                        else

                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Access" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>

    </header>
    

    @await RenderSectionAsync("Scripts", required: false)


    <div class="container-fluid">
        <div class="row flex-nowrap">
            <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                        <span class="fs-5 d-none d-sm-inline">Menu</span>
                    </a>
                    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="MY_PROJECT">
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
                            </a>
                        </li>


                        <li class="nav-item">
                            <a asp-area="" asp-controller="Home" asp-action="Privacy" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Privacy</span>
                            </a>
                        </li>



                        <li>
                            <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
                                <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span>
                            </a>

                            <ul class="collapse nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    @if (this.User.IsInRole("Admin") || this.User.IsInRole("User"))
                                    {
                                        <li class="w-100">
                                            <a class="nav-link px-0" asp-area="" asp-controller="Student" asp-action="Index">
                                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Student</span>
                                            </a>
                                        </li>
                                    }

                                    @if (this.User.IsInRole("Admin"))
                                    {
                                        <li class="w-100">
                                            <a class="nav-link px-0" asp-area="" asp-controller="Role" asp-action="Index">
                                                <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Role</span>
                                            </a>
                                        </li>
                                    }
                                }
                            </ul>
                        </li>

                        @if (User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item">
                                <a asp-area="" asp-controller="Home" asp-action="LogOut" class="nav-link px-0 align-middle">
                                    <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">logout</span>
                                </a>
                            </li>


                        }


                    </ul>


                </div>
            </div>
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>
</body>
 
</html>
<footer class="border-top footer text-muted">
    <div class="container">
        &copy;  RAJKUMAR NIRAULA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>